### ISSUE TITLE
Please clarify documentation on Qt vs. KDE and Gtk+ vs. GNOME

### ISSUE THREAD

**Issue by probonopd** [FedoraQt/adwaita-qt#101]
The documentation seems to mix Qt with KDE and Gtk+ with GNOME.

What I am looking for is the best way to make all Qt applications (including, but not limited to, KDE ones) look native on Gtk+ systems (including, but not limited to, GNOME ones).

Is this project suitable to achieving this?

**Comment by grulja** [comment]
I don't see KDE mentioned in the documentation. The purpose of adwaita-qt is to make all Qt apps (including KDE apps as those use Qt as well) to fit into Gnome Shell, means they are supposed to look they are written in GTK+ with Adwaita style. The primary target is Gnome Shell, but if you use any other DE with Adwaita style, it will have same effect.

**Comment by grulja** [comment]
To make your Qt app to use this style, you have to use "-style adwaita" parameter, or alternatively use QGnomePlatform plugin, which will be used automatically on Gtk based DEs and force to use adwaita-qt in that case when available.

**Comment by probonopd** [comment]
Thanks for the clarification @grulja 

> I don't see KDE mentioned in the documentation. 

Indeed, I was tricked by the "About KDE" dialog box. So I gake it this is not only for KDE apps but really for all Qt apps.
