### ISSUE TITLE
Drop-down list background creeping into button a bit

### ISSUE THREAD

**Issue by Eneen** [FedoraQt/adwaita-qt#102]
Plase take a look at screenshot. 
As you can see drop-down list background is bit too large. Also something is wrong with boxes on the right...
![zrzut ekranu z 2018-05-18 13-25-56](https://user-images.githubusercontent.com/25537418/40232580-abb6a99c-5a9f-11e8-80af-46817626c9e0.png)

Ubuntu 18.04
GNOME 3.28
Scribus 1.5.5 uses QT5

**Comment by MartinBriza** [comment]
There's definitely something wrong with the size calculation of the input areas.
Are you using some sort of scaling? Maybe a non-default font size?

**Comment by Eneen** [comment]
No scaling and default font. This is however Ubuntu with vanilla GNOME, maybe there's something wrong there.

**Comment by grulja** [comment]
Is this still a problem with the new version?

**Comment by Eneen** [comment]
Need to upgrade ubuntu and check. Will let you know OK? Please don't close issue.

**Comment by Eneen** [comment]
Looks like new design has solved all reported issues. Thank you!
