### ISSUE TITLE
style/adwaitastyle.cpp:5143: pointless assignment ?

### ISSUE THREAD

**Issue by dcb314** [FedoraQt/adwaita-qt#108]
adwaita-qt-1.0/style/adwaitastyle.cpp:5143:21: warning: explicitly assigning value of variable of type 'qreal' (aka 'double') to itself [-Wself-assign]

Source code is

        if (mode == AnimationHover)
            opacity = opacity;
        else if (mouseOver)

**Comment by grulja** [comment]
Fixed with https://github.com/FedoraQt/adwaita-qt/commit/19d03e53e02803a479650d6e25ca7c474f9cf867.
