### ISSUE TITLE
Excessive borders

### ISSUE THREAD

**Issue by ripefig** [FedoraQt/adwaita-qt#113]
See Kvantum for contrast - it's much cleaner

![image](https://user-images.githubusercontent.com/45201036/60533660-d1ff9d00-9d08-11e9-9f41-6a5ca5ab4651.png)

**Comment by grulja** [comment]
I'm not sure what you mean. Can you please highlight problematic part? It would also be nice to have a comparison to a gtk app, not to Kvantum, as the theme targets to look like adwaita.

**Comment by ripefig** [comment]
Sorry, forgot to take a screenshot of the problem:

![image](https://user-images.githubusercontent.com/45201036/60601958-9f62ac80-9dbb-11e9-8ff0-bfa855fd6229.png)

A closeup: 
![image](https://user-images.githubusercontent.com/45201036/60602067-c6b97980-9dbb-11e9-9703-fe37872fcbe6.png)

There are two many borders in QT apps and these borders never go to the edge of the window. For reference, just open up Nautilus and count the number of borders.

![image](https://user-images.githubusercontent.com/45201036/60602567-b524a180-9dbc-11e9-93e3-cba250286d28.png)

**Comment by grulja** [comment]
Should be fixed with https://github.com/FedoraQt/adwaita-qt/commit/7ea383c1b5ed523ba69e54fcacef08856753d530.

**Comment by ripefig** [comment]
Just tested it @grulja and it's not as good as Kvantum's version:

![image](https://user-images.githubusercontent.com/45201036/60939114-3610fb00-a2df-11e9-90df-b851f581dd75.png)

Note that with Kvantum, there is no highlight box around the active view, so it goes almost right to the edge (you have a think blue border). Also note how there is no padding around the terminal widget in Dolphin - it goes right to the edge as well. So Kvantum's implementation is much closer to what a GTK app would look like. (also see the progressbar styling above and contrast with yout glassy progress bar).

**Comment by grulja** [comment]
Goal of adwaita-qt is not to copy Kvantum Gnome theme, but look identical to Adwaita theme. If I run a Gtk application, the scrollbar have a thin border (you can still see the handle).

**Comment by grulja** [comment]
Btw. the Kvantum developer said he is not going to have 1:1 copy of Adwaita, he wants to look like it, but keep things he thinks they are nicer.

**Comment by ripefig** [comment]
The widgets and design are fundamentally different, so blindly pursuing 1:1 copy will - paradoxically - leave you with a theme that is less like Adwaita. That seems to be the persepective of the Kvantum developer too. Right now, his theme is closer to the Gnome look and feel than your theme IMO.

**Comment by ripefig** [comment]
This is especially evident with the borders and padding around widgets - GTK apps simply don't employ this design, so the borders have to be removed for better correspondence with Adwaita.

**Comment by grulja** [comment]
> This is especially evident with the borders and padding around widgets - GTK apps simply don't employ this design, so the borders have to be removed for better correspondence with Adwaita.

I'm willing to improve this situation, but you have to compare adwaita-qt with gtk adwaita, not with kvantum theme. I disabled frame rendering for locked dock widgets, which will remove borders around widgets in dolphin, have you tried the new version?
