### ISSUE TITLE
Implement alternative tab style?

### ISSUE THREAD

**Issue by ripefig** [FedoraQt/adwaita-qt#115]
This makes a big difference in terms of cleaning up the interface and making it feel closer to GTK

![image](https://user-images.githubusercontent.com/45201036/60939415-3fe72e00-a2e0-11e9-8568-0478695e3f49.png)

This again is from Kvantum. It's used for fixed tabs only, docview tabs are styled as regular tabs.

**Comment by MartinBriza** [comment]
As mentioned before, we're not trying to implement a style that's similar to a different Qt style.
Reference screenshots highlighting issues and inconsistencies in `adwaita-qt` should be taken in GTK applications.
