### ISSUE TITLE
Page number in texstudio internal pdf viewer is truncated on the left

### ISSUE THREAD

**Issue by basilrabi** [FedoraQt/adwaita-qt#118]
Version 1.1.0 in fedora 30
See:
![adwaita](https://user-images.githubusercontent.com/29010952/62105635-81fb0280-b2d5-11e9-8f7c-12a5e3e5b496.png)

**Comment by grulja** [comment]
It should be fixed with https://github.com/FedoraQt/adwaita-qt/commit/fc870303c287a3f90ab41bf8515d7f7f48b4909d. I will backport the fix to Fedora.
