### ISSUE TITLE
Cutoff text on bottom left edit box of qutebrowser

### ISSUE THREAD

**Issue by concavegit** [FedoraQt/adwaita-qt#119]
![2019-08-03-113140_958x527_scrot](https://user-images.githubusercontent.com/29216056/62411452-66983c00-b5e2-11e9-8507-8028e7a94ea1.png)
The bottom left text edit box is cut off. Perhaps this is similar to #118, but for height instead of width?

**Comment by grulja** [comment]
I don't know how to reproduce this because I don't know how to control qutebrowser. Can you guide me how to invoke the history box?

**Comment by concavegit** [comment]
Sure! `o` opens up the url entry box, which is what you are seeing. The autocomplete options that open up as well are essentially the browser's history. `Esc` closes the dialog.

**Comment by grulja** [comment]
Can you try with https://github.com/FedoraQt/adwaita-qt/commit/0a8da95fddea28e92bdd6acb7c23b5435fa220a1?

**Comment by concavegit** [comment]
It works!
