### ISSUE TITLE
Some apps use Adwaita while others not

### ISSUE THREAD

**Issue by pacho2** [FedoraQt/adwaita-qt#120]
I have installed adwaita-qt-1.1.0 and qgnomeplatform-0.5

With that two packages installed, apps like Virtualbox, LyX or QBittorrent work nice and use adwaita theme by default on Gnome without touching anything.

On the other hand, it seems that apps like calibre or picard fail to apply this theme. I need to manually export QT_STYLE_OVERRIDE=adwaita to get them using Adwaita. I wonder if this should be done by either adwaita-qt or qgnomeplatform, and why some qt apps work without it while others don't

Thanks a lot for your help

**Comment by grulja** [comment]
They don't use breeze style either when running under Plasma. To me it looks they both force to use some specific style or use their own style (like Telegram for example does).

**Comment by grulja** [comment]
Or maybe Python apps don't use QGnomePlatform (which will set that Adwaita should be used). Does QT_QPA_PLATFORMTHEME=qgnomeplatform make it work?

**Comment by grulja** [comment]
Answering to myself, nope, it doesn't help. It seems that only QT_STYLE_OVERRIDE makes a change. I will try to look why it's happening, but it's not adwaita-qt fault and most likely not even QGnomePlatform fault.

**Comment by pacho2** [comment]
OK, thanks a lot for the information :)
