### ISSUE TITLE
Same QPalette::Mid color in dark and light variant

### ISSUE THREAD

**Issue by rokm** [FedoraQt/adwaita-qt#128]
I have been looking for a way to fix VirtualBox 6 on my Fedora desktop, where it is suffering from the [UI issues with dark theme](https://www.virtualbox.org/ticket/18258). In the problematic part of the UI, the VirtualBox performs a decent amount of custom rendering with adjusted colors and gradients derived from the system-defined color palette. However, the main issue appears to be that their colors are based off the ```QPalette::Mid``` color.

The ```QPalette::Mid``` color in the dark variant of Adwaita is ```#b4b4b4```, the same as for the light variant. According to [QPalette documentation](https://doc.qt.io/qt-5/qpalette.html#ColorRole-enum), ```QPalette::Mid``` should be "Between Button and Dark.", which is not the case here - in fact, in the dark theme, this color ends up being very close to the text color.

Looking at the color palette, it seems that light and dark variant share color definitions for ```QPalette::Light```, ```QPalette::Midlight```, ```QPalette::Mid```, and ```QPalette::Dark``` (these colors are probably not defined in the original Gtk theme and are Qt-specific). These colors should probably be adjusted for the dark variant; or at least, the ```QPalette::Mid``` should be adjusted (the rest technically match the description from the Qt docs).

**Comment by grulja** [comment]
Should be fixed with https://github.com/FedoraQt/adwaita-qt/commit/d1e76197e5db24b6d1d286c6e73439d4b1a0500a. I set them according to the documentation, where the **light** color is ligher than the button color, **midlight** is between them, **dark** is darker than the button color and **mid** is between the button and dark color.

I tested it with Virtualbox and the main issue is gone. Still if I go to options, I see the top bar on the right side is still white, but I have no idea why.

**Comment by grulja** [comment]
I will backport this to Fedora.

**Comment by rokm** [comment]
> Should be fixed with [d1e7619](https://github.com/FedoraQt/adwaita-qt/commit/d1e76197e5db24b6d1d286c6e73439d4b1a0500a). I set them according to the documentation, where the **light** color is ligher than the button color, **midlight** is between them, **dark** is darker than the button color and **mid** is between the button and dark color.
> 
> I tested it with Virtualbox and the main issue is gone. 

Thanks, this indeed fixes the main issue with the UI!

> Still if I go to options, I see the top bar on the right side is still white, but I have no idea why.

That (and couple other quirks) needs to be addressed in the VirtualBox itself.

**Comment by John15321** [comment]
Is there any way to submit that to Virtual Box so that they fix that?
