### ISSUE TITLE
style/adwaitahelper.cpp: 4 * duplicated branches

### ISSUE THREAD

**Issue by dcb314** [FedoraQt/adwaita-qt#129]
1.

At line 613,

            if (darkMode) {
                gradient.setColorAt(0, color);
                gradient.setColorAt(1, color);
            } else {
                // Pressed button in normal mode is not a gradient, just an image consting from same $color
                gradient.setColorAt(0, color);
                gradient.setColorAt(1, color);
            }

Duplicates at lines 689, 1046, 1208.

Maybe something similar at 

adwaita-qt-1.1.1/style/adwaitastyle.cpp:4415:12: warning: this condition has identical branches [-Wduplicated-branches]

**Comment by grulja** [comment]
Fixed with https://github.com/FedoraQt/adwaita-qt/commit/2f7352a2fb37479a2d9efe4956404717a78cba70.
