### ISSUE TITLE
Publish it as a Flatpak runtime extension on FlatHub

### ISSUE THREAD

**Issue by xcffl** [FedoraQt/adwaita-qt#131]
It would be great if we can publish adwaita-qt as a Flatpak extension on FlatHub as [what QGnomePlatform does](https://github.com/flathub/org.kde.PlatformTheme.QGnomePlatform/blob/branch/5.12/org.kde.PlatformTheme.QGnomePlatform.json). That will make it possible for Qt apps running on Gnome environment distributed as Flatpaks look native, as what I'm trying to implement at https://github.com/flathub/com.calibre_ebook.calibre/issues/34.

I'd like to help with this if needed.

**Comment by grulja** [comment]
It's already there as org.kde.KStyle.Adwaita.
