### ISSUE TITLE
Anki is weirdly colored

### ISSUE THREAD

**Issue by memeplex** [FedoraQt/adwaita-qt#133]
![image](https://user-images.githubusercontent.com/2845433/78121251-8c7c1780-73e1-11ea-89fb-72badcb527d1.png)

Versions:
* Anki:  2.1.15 
* Gnome: 3.36.0
* adwaita-qt: latest master

**Comment by memeplex** [comment]
I don't know if this helps but that what they said at Anki's forums about the webview:

> Anki sets the webview to the window color: `return self.style().standardPalette().color(QPalette.Window)`

**Comment by grulja** [comment]
> I don't know if this helps but that what they said at Anki's forums about the webview:
> 
> > Anki sets the webview to the window color: `return self.style().standardPalette().color(QPalette.Window)`

That helps, thank you. If I implement standardPalette() in Adwaita, then I can change the color, however with dark theme it still looks weird as it uses black color for text. I will look how to implement it properly and let you know.

**Comment by memeplex** [comment]
Here is some additional info:

> please note that Anki can not automatically cope with dark themes, but if switched to night mode in the preferences it will use white text.

**Comment by memeplex** [comment]
BTW this is the thread https://anki.tenderapp.com/discussions/ankidesktop/40699-wrong-colors-using-adwaita-qt-theme

**Comment by grulja** [comment]
Should be fixed with https://github.com/FedoraQt/adwaita-qt/commit/ebd3ff2f1a3259f18d691a360a411c266421f6e3.

**Comment by memeplex** [comment]
Thanks!
