### ISSUE TITLE
Some fonts result in wrong weight being used

### ISSUE THREAD

**Issue by asegarra** [FedoraQt/adwaita-qt#134]
Certain fonts when selected result in the theme displaying them with a higher weight e.g. Light looks Regular, Regular look Medium or Bold. Examples of fonts that display like this are Cantarell, Fira Sans, Source Sans Pro.
Other fonts don't appear to be affected like Ubuntu Mono, Roboto, Liberation.

The reason I believe the problem is in the theme is that if I switch Qt themes like Breeze and Fusion the fonts look as they should.

These screen shots are both using Cantarell Regular font:

Adwaita:
![adwaita](https://user-images.githubusercontent.com/12531275/78916398-68f94280-7a5b-11ea-9776-fc399828ffeb.png)

Fusion:
![non-adwaita](https://user-images.githubusercontent.com/12531275/78916408-6c8cc980-7a5b-11ea-9f59-41dca6d97af5.png)

**Comment by grulja** [comment]
It looks like a bug in the Cantarell font.

See https://bugzilla.redhat.com/show_bug.cgi?id=1823984.

**Comment by asegarra** [comment]
Hi, but does that mean those other fonts I mentioned have bugs? Why do I only see this if I use adwaita-qt ?
