### ISSUE TITLE
With Scribus, all symbols (characters ?) are missing in Insert > Shapes submenus

### ISSUE THREAD

**Issue by antistress** [FedoraQt/adwaita-qt#135]
Hi,

I've just installed latest net.scribus.Scribus from FlatHub (note that it's the 1st time I launch Scribus).

In french, menu Insérer > Forme > "Formes par défaut" is empty.
Items can be selected and you can click on it but there is no visible labels.

Same for other entries below "Formes par défaut" : "Flèches", "Organigramme", "Casse-tête" and "Caractères spéciaux".

In english corresponding entries are Insert > Shape > …

See screenshot below.

It seems to be an issue with the Adwaita theme since another user was able to reproduce this bug with Adwaita theme whereas every things work as expected with Fusion theme (see https://github.com/flathub/net.scribus.Scribus/issues/14#issuecomment-612620354)

Thanks !

![Capture d’écran de 2020-04-12 13-14-07](https://user-images.githubusercontent.com/2436957/79072886-fe523c00-7cd2-11ea-89e6-40b37e609502.png)

**Comment by grulja** [comment]
Fixed with https://github.com/FedoraQt/adwaita-qt/commit/f91b110b0888d292766de92842f10aae6b745b25.

**Comment by grulja** [comment]
I will try to fix some other reported issues, make a new release and update adwaita-qt in Flathub so you can use Scribus as soon as possible. Thanks.

**Comment by antistress** [comment]
Thanks !
& no hurry :)

**Comment by antistress** [comment]
I guess it the same bug for the text editor ?

See screenshot below :
![Scribus text editor](https://user-images.githubusercontent.com/2436957/79085074-a3e2cb00-7d26-11ea-95f8-003e0c06016a.png)

Thanks
