### ISSUE TITLE
Missing fonts on Paraview with Adwaita-Dark

### ISSUE THREAD

**Issue by jvellojin** [FedoraQt/adwaita-qt#144]
Dear developers,

On Paraview, there are missing fonts when using Adwaita. I'm using qt5ct to apply the theme, with the corresponding environment variable QT_QPA_PLATFORMTHEME=qt5ct. The fonts don't appear when opening filters by alphabetical order (see screenshots below). This is not the case when using, for example, Fusion.

Distro: Arch-Linux
DE: GNOME 3.38
Paraview version:  5.8.1
Adwaita-Qt version: 1.1.4-2

![imagen](https://user-images.githubusercontent.com/47927225/96377142-d8ae5f80-1159-11eb-999c-1298ec566780.png)
![imagen](https://user-images.githubusercontent.com/47927225/96377173-157a5680-115a-11eb-8ff3-b400839e504f.png)

**Comment by grulja** [comment]
This has been fixed already with https://github.com/FedoraQt/adwaita-qt/pull/142 and will be part of the next Adwaita release. For now you can either install the beta version of upcoming release or just apply this patch to Adwaita 1.1.4.

**Comment by jvellojin** [comment]
Thanks for the hard work!
