### ISSUE TITLE
AdwaitaQt=1.2.50?

### ISSUE THREAD

**Issue by dariusity** [FedoraQt/adwaita-qt#149]
I tried to build QGnomePlatform but it needed Adwaita-Qt=1.2.50 but your release is only 1.2.0? I have "adwaita-qt-git-1.2.0.r7.g4ec3d95-1.pkg.tar.xz"

Isit due to difference in versioning packages between distros? Im compiling it from AUR. Cheers.

**Comment by grulja** [comment]
It currently depends on development version of adwaita-qt, because I'm working on both simultaneously. You will need to build Adwaita-qt from master and then you will be able to build QGnomePlatform.
