### ISSUE TITLE
make: *** No targets specified and no makefile found.  Stop.

### ISSUE THREAD

**Issue by lefthairynut** [FedoraQt/adwaita-qt#150]
when I try to build the package I get the following message: `make: *** No targets specified and no makefile found.  Stop.`
distro: arch linux

**Comment by grulja** [comment]
Did you run CMake command in the same folder where you run make?

**Comment by lefthairynut** [comment]
yes. and I tried building it manually and with [adwaita-qt](https://aur.archlinux.org/packages/adwaita-qt/) and [adwaita-qt-git](https://aur.archlinux.org/adwaita-qt.git) at first I thought its the packaging fault but all the above yields the same error.

**Comment by grulja** [comment]
Can you check whether CMake found all the dependencies? Can you post the full log from CMake here so I can check?

**Comment by lefthairynut** [comment]
uh, I ended reinstalling the arch and the problem resolved on its own. I think I fucked up my qt. Thanks for the support anyways!
