### ISSUE TITLE
Qt applications have invisible window controls in Fedora 34

### ISSUE THREAD

**Issue by wm75** [FedoraQt/adwaita-qt#152]
I just hope this is the right place to report my issue, but I upgraded to Fedora 34 yesterday and I'm observing that Qt-based applications (nomacs, mumble, eric IDE) have hardly visible window controls without focus, which become completely invisible when the window takes focus.

Example without focus:
![nomacs_without_focus](https://user-images.githubusercontent.com/4742081/116879088-80840a00-ac20-11eb-8ce3-eb098c8d0657.png)

Example with focus:
![nomacs_with_focus](https://user-images.githubusercontent.com/4742081/116879091-811ca080-ac20-11eb-8b9a-b412357d8767.png)

Is this a known issue or something that may be just a config issue on my side?

**Comment by grulja** [comment]
Was this also a problem on Fedora 33? Do you use different style/theme or default Adwaita?

**Comment by wm75** [comment]
I upgraded from Fedora 32 so cannot comment on 33. I'm using the default Adwaita theme (but Papirus-Dark *icon* theme if that should matter).

**Comment by wm75** [comment]
> but Papirus-Dark icon theme if that should matter

In fact, it *does* matter. Didn't even remember that fact before you asked, now switched to Adwaita also as the icon theme and that "fixes" it.
Just that it prevents me from using my beloved Papirus icon theme.

**Comment by grulja** [comment]
Yes, that will be the reason. It should be fixed in upcoming QGnomePlatform release, where I don't use icons from the icon theme, but I paint them myself.
