### ISSUE TITLE
cmake version requirement 3.18

### ISSUE THREAD

**Issue by Idesmi** [FedoraQt/adwaita-qt#156]
Cmake version 3.18 [doesn't seem](https://build.opensuse.org/package/show/home:iDesmI:branches:GNOME:Apps/adwaita-qt) to be necessary to build adwaita-qt 1.4.0

openSUSE Leap 15.3 ships with cmake 3.17, so please consider lowering the required version.

**Comment by grulja** [comment]
Fixed with https://github.com/FedoraQt/adwaita-qt/commit/c9dff168c1f019a2113f4bcb08fb1bd7f32540cd.
