### ISSUE TITLE
Unreadable contrast for Adwaita

### ISSUE THREAD

**Issue by John15321** [FedoraQt/adwaita-qt#157]
In certain apps, some of their sections show up with such contrast that they become unreadable. An example is Virtual Box preferences:

![image](https://user-images.githubusercontent.com/56229312/133926580-e4adf599-2ad1-4c23-a5c1-f54e7a89bf70.png)

As you can see the "General" title is barely visible. Problems like that occur also in other apps. And sometimes because of that issue, some parts of the UI, where for example important buttons are located are not visible at all which is very problematic
Here are my settings (I didn't mess with the settings at all so they should be vanilla, btw this issue is also present on other distros):

![image](https://user-images.githubusercontent.com/56229312/133926603-05dafd52-25f0-44b7-9404-16ea39c18e74.png)

**Comment by grulja** [comment]
This I think has to be fixed in Virtualbox itself, see https://github.com/FedoraQt/adwaita-qt/issues/128#issuecomment-564473495.
