### ISSUE TITLE
Slide horizontal setting widgets in Krita

### ISSUE THREAD

**Issue by bogdancovaciu** [FedoraQt/adwaita-qt#159]
Hello,

By default, the brush Opacity and Size widgets in Krita look like this:

![image](https://user-images.githubusercontent.com/37552419/138701250-33a6b6f0-c860-4866-8ac3-ecf629b042e7.png)

With latest Adwaita-qt, kcoreaddons 5.87 and qt5 5.15.2 i get this:

![image](https://user-images.githubusercontent.com/37552419/138701578-e5460bb8-861f-420d-9709-a1d2863bdee3.png)

The slide goes on vertical, squeezed, instead of horizontal.

Reproducible on KDE Plasma and Gnome while using the profile `export KRITA_NO_STYLE_OVERRIDE=1` because i want to get rid of the default Fusion style used for it.

**Comment by grulja** [comment]
This is weird, because I have QProgressBar in my demo/test application and it is correct (both variants). Also, when I check the source code of QProgressBar, I can see that, when the orientation is horizontal, it updates QStyleOption->state, which is what we check in order to distinguish between horizontal and vertical orientation.

Have you seen similar issue in some other application?

**Comment by bogdancovaciu** [comment]
Actually Krita is the only one that has those `Brush option slider`s. Not sure if are related to QProgressBar, or simply something only they use for horizontalSlider > QSlider and doesn't match, only if using their default Fusion style or the Breeze one. Will try to contact one of the developers from Krita and see if i get a hint.

**Comment by grulja** [comment]
I will keep digging, because it works with Fusion and Breeze so there actually might be something wrong with Adwaita.

**Comment by bogdancovaciu** [comment]
The only real issue is when booting in Gnome, as i always test between KDE Plasma and Gnome, not mixing them, and i prefer to keep things consistent. But even in KDE Plasma i prefer to use Adwaita, has the best contrast for my eyes, and each element a proper "footprint" on screen. One thing i notice in preview, the difference of those sliders, but they render properly.

![image](https://user-images.githubusercontent.com/37552419/141081811-54491e03-0d27-4558-823d-6002dd4a51ae.png)

Only Krita has them somehow acting funky.

**Comment by grulja** [comment]
Should be fixed with https://github.com/FedoraQt/adwaita-qt/commit/85670f8f2f61fd10f867d55555282d0951925160.
