### ISSUE TITLE
libadwaita-qt5 is not signed

### ISSUE THREAD

**Issue by jagjordi** [FedoraQt/adwaita-qt#163]
First of all, excuse me if this is not the correct place to post about this problem, but I don't know where else I could post.
I am trying to install libadwaita-qt5 into RHEL8 from [Raven repository](https://centos.pkgs.org/8/raven-x86_64/libadwaita-qt5-1.4.1-1.el8.x86_64.rpm.html). I get the following error
`Package libadwaita-qt5-1.4.1-1.el8.x86_64.rpm is not signed`
`Error: GPG check FAILED` 
I can bypass GPG with `dnf install libadwaita-qt5 --nogpgcheck` ,but I wanted to ask if it is possible to solve the problem while maintaining GPG check.

**Comment by grulja** [comment]
Hi, this is a packaging/repo issue, not something I can do anything about.
