### ISSUE TITLE
Dolphin looks light with dark themes

### ISSUE THREAD

**Issue by Akergez** [FedoraQt/adwaita-qt#164]
![image](https://user-images.githubusercontent.com/78296459/150580708-a72d2c76-17b3-4e3f-a893-60e8fd34f036.png)

**Comment by eskiq** [comment]
https://wiki.archlinux.org/title/Dolphin#Mismatched_folder_view_background_colors

**Comment by grulja** [comment]
Duplicate of https://github.com/FedoraQt/adwaita-qt/issues/151.
