### ISSUE TITLE
Update to look like libadwaita

### ISSUE THREAD

**Issue by sharpenedblade** [FedoraQt/adwaita-qt#166]
Make qt apps look like the new libadwaita theme, which is what most of gnome will look like.

**Comment by sith-on-mars** [comment]
Maybe [adw-gtk3](https://github.com/lassekongo83/adw-gtk3#adw-gtk3) can be of help?

**Comment by yann-boyer** [comment]
> Maybe [adw-gtk3](https://github.com/lassekongo83/adw-gtk3#adw-gtk3) can be of help?

Adw-gtk3 only covers GTK3 applications, nothing about Qt apps.

I think it's really important to its developers to update AdwaitaQt to look like libadwaita, I think system theme coherence is really important, more important than several people think.

**Comment by daudix-UFO** [comment]
Agree, it's very important

**Comment by Aleksanaa** [comment]
any work on this?

**Comment by grulja** [comment]
> any work on this?

I'm sorry, but there is no update on this. This is going to be a lot of work and at this moment I don't have time for it.

**Comment by sith-on-mars** [comment]
There is [KvLibadwaita](https://github.com/GabePoel/KvLibadwaita) for Kvantum, which is pretty new, but making a lot of progress.

**Comment by Aleksanaa** [comment]
> There is [KvLibadwaita](https://github.com/GabePoel/KvLibadwaita) for Kvantum, which is pretty new, but making a lot of progress.

There is still a problem kvLibadwaita could not fix:since gnome team has decided not to draw window border in wayland,qt draws window border itself,and adwaita-qt is the only theme that can change border styles.i didn't see any kvantum theme changing border styles,and they all just look like breeze in different colors.

**Comment by paerbac** [comment]
issue still present

**Comment by dnkmmr69420** [comment]
it would be nice if there is a libawdita qt

**Comment by nonetrix** [comment]
Pretty much all the core apps have been upgrade to GTK4 I think it's time this is updated +1

**Comment by Movisivi** [comment]
> > any work on this?
> 
> I'm sorry, but there is no update on this. This is going to be a lot of work and at this moment I don't have time for it.

Its been nearly a year now, no way you're SOOOOOOOO busy you can't dedicate a few hours a day to close this issue. Lazy developer.

**Comment by Movisivi** [comment]
For now usehttps://github.com/urFate/QAdwaitaPlatform until the devs get their shit together

**Comment by MartinBriza** [comment]
please be aware that writing comments in such tone will not make any developer start working on whatever you request, on the contrary, it just brings sour taste to working on the project... i noticed you wrote multiple extremely rude and negative comments recently, i just want to reiterate these won't achieve us working on the issues in question but if you continue, we'll just report you to github

**Comment by paerbac** [comment]
> > > any work on this?
> > 
> > I'm sorry, but there is no update on this. This is going to be a lot of work and at this moment I don't have time for it.
> 
> Its been nearly a year now, no way you're SOOOOOOOO busy you can't dedicate a few hours a day to close this issue. Lazy developer. 

Don't call a developer's work lazy when they are working on an open source project that is available to you FOR FREE. If you have a problem, it's open source, you can fork it, or create your own pull request.

**Comment by grulja** [comment]
> For now use https://github.com/urFate/QAdwaitaPlatform until the devs get their shit together

This is not a replacement for Adwaita-qt, but only for client-side decorations provided by QGnomePlatform.

> > > any work on this?
> > 
> > 
> > I'm sorry, but there is no update on this. This is going to be a lot of work and at this moment I don't have time for it.
> 
> Its been nearly a year now, no way you're SOOOOOOOO busy you can't dedicate a few hours a day to close this issue. Lazy developer.

I'm actually and Adwaita-qt and QGnomePlatform are not the only projects I work on. Feel free to read what I've been up to instead on my blog https://jgrulich.cz/. I don't really consider myself as a lazy developer.

Anyway, back to this topic. I'm not going to implement this change/request at all, in fact, I'm going to discontinue Adwaita-qt and QGnomePlatform projects. The plan is to upstream all the QGnomePlatform features to Qt upstream so we don't play on our own playground and replace Adwaita-qt with Fusion/Breeze. This is going to be done as part of Fedora 39 change as proposed here: https://fedoraproject.org/wiki/Changes/NoCustomQtThemingForWorkstation.

**Comment by nonetrix** [comment]
> For now use https://github.com/urFate/QAdwaitaPlatform until the devs get their shit together

This is a good stopgap solution, but please don't be rude about it. Also, maybe it could be useful in updating adwaita-qt? Or maybe even replace it, but I think the latter would have to include making Kvantum a dependency which I imagine Fedora wouldn't want to do probably

**Comment by deusnovus** [comment]
> The plan is to upstream all the QGnomePlatform features to Qt upstream so we don't play on our own playground and replace Adwaita-qt with Fusion/Breeze. This is going to be done as part of Fedora 39 change as proposed here: https://fedoraproject.org/wiki/Changes/NoCustomQtThemingForWorkstation.

If I understood correctly, the proposal in the link above suggests Fedora 39+ could be auto-implementing native libadwaita decorations to any qt applications, right? This is amazing news, but if it's upstreamed straight to qt, surely that would also affect all distros running GNOME, not just Fedora right?

**Comment by sky96111** [comment]
> > The plan is to upstream all the QGnomePlatform features to Qt upstream so we don't play on our own playground and replace Adwaita-qt with Fusion/Breeze. This is going to be done as part of Fedora 39 change as proposed here: https://fedoraproject.org/wiki/Changes/NoCustomQtThemingForWorkstation.
> 
> If I understood correctly, the proposal in the link above suggests Fedora 39+ could be auto-implementing native libadwaita decorations to any qt applications, right? This is amazing news, but if it's upstreamed straight to qt, surely that would also affect all distros running GNOME, not just Fedora right?

No. According to the proposal on  Fedora 39+ , default decoration will nolonger be adwaita-qt but breeze. Just like Arch

**Comment by deusnovus** [comment]
Oh I see, thanks for clarifying it. That's unfortunate for those who want a "libadwaita everything" environment.

**Comment by Movisivi** [comment]
This is a very dumb decision and a middle finger to GNOME and Fedora users alike.

**Comment by nonetrix** [comment]
I understand the decision, but perhaps someone should fork this repo and continue development so people have the option to use a up to date theme

**Comment by deusnovus** [comment]
> I understand the decision, but perhaps someone should fork this repo and continue development so people have the option to use a up to date theme

I hope that will be the case eventually. I'm not very good at programming so it's not my place to complain, but this feels like a regression all together and don't quite understand who is this new proposal for.

**Comment by sharpenedblade** [comment]
The change proposal explains the reasoning behind this. From the linked change:

> These projects are now in a state where they are outdated and semi-occasionally broken for some applications and it would be better to default to what Qt upstream has to offer.

> There is no equivalent of such style in Qt, but given the complexity of Qt Style plugins, this project is now outdated and doesn't match the current Adwaita (GTK4) style. It is also responsible for the most of the issues users are facing while using our custom styling.

> This will also eliminate all the issues our users have been experiencing in the past when using Qt applications with Adwaita-qt style on Fedora Workstation.
