### ISSUE TITLE
When the colour scheme is prefer-dark can adwaita-qt use a dark variant?

### ISSUE THREAD

**Issue by ahayzen** [FedoraQt/adwaita-qt#172]
When the user has chosen the preference of a dark colour scheme in GNOME Settings (which I believe causes `gsettings get org.gnome.desktop.interface color-scheme` to become `prefer-dark` ?). Can the adwaita-qt theme be changed to match when Adwaita-Dark is used?

**Comment by grulja** [comment]
Adwaita-qt itself doesn't check GNOME configuration. This is achieved using QGnomePlatform. I made some changes to this in upcoming version of QGnomePlatform and apps will change dark/light variant even on runtime.
