### ISSUE TITLE
`wireshark -style adwaita` still white

### ISSUE THREAD

**Issue by vitaly-zdanevich** [FedoraQt/adwaita-qt#175]
I want dark theme :(

Gentoo, i3, X11.

**Comment by grulja** [comment]
Use `wireshark -style adwaita-dark`. Do you also use QGnomePlatform? With QGnomePlatform you should have correct variant applied automatically.

**Comment by vitaly-zdanevich** [comment]
> `wireshark -style adwaita-dark`

Thanks, now Wireshark is dark:
![image](https://user-images.githubusercontent.com/3514015/183363469-5b002dd4-710f-4f13-8b86-5584ec9f2cb9.png)

I do not have QGnomePlatform, should I install it?

**Comment by grulja** [comment]
> I do not have QGnomePlatform, should I install it?

Yes, at least in case you use GNOME. It's a Qt Platform Theme that will further integrate Qt apps with GNOME. It will read your GNOME configuration and apply it to your Qt applications so things like font, icon theme, window decorations (wayland) etc. will be same as for your other apps.

**Comment by vitaly-zdanevich** [comment]
I do not have Gnome, I have i3 only.

Can I apply `-style adwaita-dark` for all qt apps?

> It will read your GNOME configuration and apply it to your Qt applications

Its a daemon that will eat my RAM?

**Comment by grulja** [comment]
> I do not have Gnome, I have i3 only.

In that case it will be probably useless.

> Can I apply `-style adwaita-dark` for all qt apps?
> 

Yes. You can do that by env variable `QT_STYLE_OVERRIDE=adwaita-dark` in .bashrc or somewhere.

> > It will read your GNOME configuration and apply it to your Qt applications
> 
> Its a daemon that will eat my RAM?

No, not really. Qt always loads some platform theme plugin, it just depends on desktop you use and available plugins, but there is always one needed to be loaded. If QGnomePlatform is not installed, Qt will use some basic they have implemented internally. For example KDE Plasma desktop also has its own implementation of Qt Platform Theme, this is just an essential part of Qt when it comes to theming and integration.
