### ISSUE TITLE
Rendering of menus doesn't look right

### ISSUE THREAD

**Issue by nparkanyi** [FedoraQt/adwaita-qt#178]
- The little blue highlight bar is missing on the selected menu
- Poor contrast on the submenu arrow
- The selection rectangle seems to spill outside the boundary a bit
![adwaitaqt_menu](https://user-images.githubusercontent.com/2218162/190291587-0b1b381c-3f3c-4f0a-9e6c-c3b585d8df0d.png)

**Comment by nparkanyi** [comment]
With this:
```
--- a/src/style/adwaitastyle.cpp
+++ b/src/style/adwaitastyle.cpp
@@ -4932,7 +4932,7 @@ bool Style::drawMenuBarItemControl(const QStyleOption *option, QPainter *painter
     if (useStrongFocus && sunken) {
         StyleOptions styleOptions(painter, QRect(rect.left(), rect.bottom() - 2, rect.width(), 3));
         styleOptions.setColorVariant(_variant);
-        styleOptions.setOutlineColor(Colors::focusColor(StyleOptions(palette, _variant)));
+               styleOptions.setColor(Colors::focusColor(StyleOptions(palette, _variant)));
         Adwaita::Renderer::renderFocusRect(styleOptions);
     }
```
the highlight rectangle shows up (though it's not the right shade of blue).
![adwaitaqt_menu2](https://user-images.githubusercontent.com/2218162/190294055-4883c2b8-1f34-4661-96d5-0cb97ac37432.png)

**Comment by grulja** [comment]
Fixed with https://github.com/FedoraQt/adwaita-qt/pull/179.
