### ISSUE TITLE
qbittorrent does not see the theme

### ISSUE THREAD

**Issue by Yasand123** [FedoraQt/adwaita-qt#180]
When running `qbittorrent -style adwaita` I get the following error:
```
QApplication: invalid style override 'adwaita' passed, ignoring it.
	Available styles: qt6ct-style, Windows, Fusion
```
Is it because qbittorrent is qt6? I also couldn't find the theme using qt6 settings app, but I found it using the qt5 one.

I also tried systemsettings, I set the theme to adwaita, same issue. qbittorrent will just ignore everything.

Context:
- GNOME 42.4
- Arch Linux
- I had KDE Plasma installed prior to installing GNOME, so both are installed currently, but I'm using GNOME and the issue is from within the GNOME shell.

**Comment by MartinBriza** [comment]
This is a binary Qt style and major Qt versions are not binary compatible, so you need to have adwaita-qt built against all Qt versions you want to use it with. I'll close the ticket but feel free to get in touch if you need more information.
