### ISSUE TITLE
Issues with qt6 in wayland

### ISSUE THREAD

**Issue by moshiur-raj** [FedoraQt/adwaita-qt#181]
![image](https://user-images.githubusercontent.com/36466700/192091896-c0f142c2-af5c-47d7-bc39-09dc83da3078.png)

A glitch? appears in the bottom right corner when moving qbittorrent in wayland session. This does not happen when using xwayland or the breeze theme.

**Comment by grulja** [comment]
This is a bug in Qt 6 that has been fixed recently, possibly be available with Qt 6.4 (not sure). In Fedora this change has been already backported so you can talk to your distro packagers and ask them to pick the fix right away. It's here: https://src.fedoraproject.org/rpms/qt6-qtwayland/blob/rawhide/f/0100-Keep-toplevel-windows-in-the-top-left-corner-of-the-screen.patch
