### ISSUE TITLE
Update adwaita gtk4 theme

### ISSUE THREAD

**Issue by vollowx** [FedoraQt/adwaita-qt#190]
As the title says, there are only gtk3 themes now in this repo.

**Comment by xgugugu** [comment]
![截图 2023-05-30 21-31-14](https://github.com/FedoraQt/adwaita-qt/assets/85472190/41ebdba3-cc75-4602-88b0-7b71d1d55a2d)
![截图 2023-05-30 21-31-20](https://github.com/FedoraQt/adwaita-qt/assets/85472190/d72a8979-3560-4ceb-ac30-5e4c716cb3be)

**Comment by huge-pancake** [comment]
Looks really nice

**Comment by Movisivi** [comment]
So when will this get pushed
