### ISSUE TITLE
Large (and pixelated) clear icon in QLineEdit

### ISSUE THREAD

**Issue by CDrummond** [FedoraQt/adwaita-qt#54]
When a QLineEdit is set to show a clear button ( QLineEdit.setClearButtonEnabled(true) ) Adwaita-Qt5 draws too large an icon, and it is very pixelated. See the following screenshot from QtDesigner from Fedora 25:

![qlineedit](https://cloud.githubusercontent.com/assets/1141694/21430400/f9ce0450-c85a-11e6-8264-d733380133f8.png)

**Comment by MartinBriza** [comment]
Thanks for the report. I'll have to find out where is this rendered first... it's not as obvious as I thought it would be.

**Comment by CDrummond** [comment]
Also, the icon appears fine with Ubuntu GNOME 16.10

**Comment by MartinBriza** [comment]
Seems we won't be able to do anything about this because of this hack in Qt: https://code.woboq.org/qt5/qtbase/src/widgets/widgets/qlineedit_p.cpp.html#434 which is what I believe is responsible for the size of the arrow.

**Comment by CDrummond** [comment]
Perhaps this fix from Kvantum could be used? https://github.com/tsujan/Kvantum/commit/3fc4229a195a9626bf63066b88dc7eb433c8d1cc

I would try the fix myself, but I'm currently unable to recreate the issue!

**Comment by Esokrates** [comment]
@MartinBriza Could you look into this again? What's the status of this? Should we file a bug against Qt? Please propose what needs to happen in order to fix this.

**Comment by grulja** [comment]
I cannot reproduce with latest Adwaita-qt release. Tested on both X11 and Wayland. Feel free to reopen if you are still able to reproduce it.
