### ISSUE TITLE
Submit this to distros!

### ISSUE THREAD

**Issue by Pointedstick** [FedoraQt/adwaita-qt#93]
This is so awesome that it ought to show up in distros' package managers! Probably Debian + downstream, Fedora, openSUSE, and Arch. May be able to do all of them at once from an OBS repo.

**Comment by MartinBriza** [comment]
Thanks for the kind words. :) Well, to be completely honest, I'm not really looking to maintain the package for all distributions. It's already in Fedora (and likely in Arch) and I assume Ubuntu guys will pick it up themselves soon, too.
You suggest putting it into OBS, that may be a good idea though, as it's not a huge amount of work for me. I'll see what I can do about it.

**Comment by mitya57** [comment]
For the record, I am maintaining this package in Debian + derivatives. See https://tracker.debian.org/pkg/adwaita-qt.

**Comment by grulja** [comment]
Feel free to put this into OBS or ping distro maintainers to package this theme. At this moment we don't have capacity to do that. We have adwaita-qt available in Flathub for those using Qt apps in Flatpak.

Given we are not going to do anything about this, I will now close this issue.
