### ISSUE TITLE
Problem with VirtualBox version 5.2.2 r119230 (Qt5.6.1)

### ISSUE THREAD

**Issue by orschiro** [FedoraQt/adwaita-qt#98]
Dear all, 

I successfully compiled the style and tried to apply it to the latest version of VirtualBox but it doesn't take the style. 

Can anyone advice me what I am doing wrong?

Thank you!

![image](https://user-images.githubusercontent.com/170947/34095351-6161fdbe-e3d1-11e7-84cc-45da3a0ee6fa.png)

**Comment by nemanjan00** [comment]
QT_STYLE_OVERRIDE=adwaita-dark virtualbox

**Comment by orschiro** [comment]
@nemanjan00 thanks so much! Currently have no Linux Mint installed to test. :-()

**Comment by nemanjan00** [comment]
![screenshot from 2018-05-24 16-48-58](https://user-images.githubusercontent.com/448151/40493145-62d5bd9e-5f72-11e8-9301-7b0b1bdf6c7b.png)

**Comment by orschiro** [comment]
Yeah, looks good to me! :-D
