### ISSUE TITLE
KeePassXC has a too large search bar

### ISSUE THREAD

**Issue by FalkAlexander** [FedoraQt/adwaita-qt#99]
The search bar / search icon is too large.
![adwaita](https://user-images.githubusercontent.com/5732964/35198870-ff14c68c-feec-11e7-844e-6bdf0de4816a.png)
Original behaviour:
![plain](https://user-images.githubusercontent.com/5732964/35198873-0d26973c-feed-11e7-9517-3cf7d3067004.png)

**Comment by grulja** [comment]
I believe this is fixed in the new version.
